spring:
  application:
    name: com

weather:
   api:
     base-url: https://api.open-meteo.com/v1/



#     https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&hourly=temperature_2m&current_weather=true
